# Generated by Django 3.2.17 on 2023-03-15 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='carro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=100, verbose_name='Placa')),
                ('entrada', models.DateTimeField(verbose_name='Entrada')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parqueadero.tipo')),
            ],
        ),
    ]
